In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns",None)

In [ ]:
df = pd.read_csv("final_healthcare_master.csv")

df.head()

,ranking,district,state,population,growth,sex_ratio,literacy,health_centres,population_per_health_centre,healthcare_density,healthcare_rank,electricity,clean_fuel,health_insurance,female_literacy,antenatal_care,institutional_birth,vaccination,stunted,underweight,anaemia
0,1,THANE,MAHARASHTRA,11060148.0,36.01 %,886,84.53,336.0,3.291711e+04,Poor,134.0,99.29,90.40,22.73,90.49,70.19,93.62,-74.9,40.76,30.81,58.82
1,2,NORTH TWENTY FOUR PARGANAS,WEST BENGAL,10009781.0,12.04 %,955,84.06,870.0,1.150550e+04,Average,7.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
2,3,BANGALORE,KARNATAKA,9621551.0,47.18 %,916,87.67,0.0,9.621551e+06,Critical,361.0,98.78,97.20,28.83,87.27,74.60,99.34,-78.16,31.26,28.09,35.54
3,4,PUNE,MAHARASHTRA,9429408.0,30.37 %,915,86.15,773.0,1.219846e+04,Average,16.0,99.37,89.49,14.42,89.01,68.59,97.97,-58.08,30.70,32.66,51.93
4,5,MUMBAI SUBURBAN,MAHARASHTRA,9356962.0,8.29 %,860,89.91,0.0,9.356962e+06,Critical,361.0,99.17,98.68,20.19,91.58,72.20,98.08,*,37.23,24.59,49.97

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ranking                       610 non-null    int64
 1   district                      610 non-null    object
 2   state                         610 non-null    object
 3   population                    610 non-null    float64
 4   growth                        610 non-null    object
 5   sex_ratio                     610 non-null    int64
 6   literacy                      610 non-null    float64
 7   health_centres                610 non-null    float64
 8   population_per_health_centre  610 non-null    float64
 9   healthcare_density            610 non-null    object
 10  healthcare_rank               610 non-null    float64
 11  electricity                   610 non-null    float64
 12  clean_fuel                    610 non-null    float64
 13  health_insurance              610 non-null    float64
 14  female_literacy               610 non-null    float64
 15  antenatal_care                610 non-null    float64
 16  institutional_birth           610 non-null    float64
 17  vaccination                   555 non-null    object
 18  stunted                       610 non-null    float64
 19  underweight                   610 non-null    float64
 20  anaemia                       610 non-null    float64
dtypes: float64(14), int64(2), object(5)
memory usage: 100.2+ KB

In [ ]:
df.describe()

,ranking,population,sex_ratio,literacy,health_centres,population_per_health_centre,healthcare_rank,electricity,clean_fuel,health_insurance,female_literacy,antenatal_care,institutional_birth,stunted,underweight,anaemia
count,610.000000,6.100000e+02,610.000000,610.000000,610.000000,6.100000e+02,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000,610.000000
mean,329.598361,1.845019e+06,944.914754,72.344344,246.536066,2.761732e+05,213.416393,97.038098,51.932508,38.818770,74.859328,59.748951,89.038016,33.111852,29.159066,55.515131
std,184.656903,1.566814e+06,61.247694,10.540881,204.643130,9.709090e+05,108.546693,4.168374,21.779149,22.335061,11.880963,20.316476,11.556841,8.545917,9.675870,11.536931
min,1.000000,8.004000e+03,534.000000,36.100000,0.000000,1.020304e+03,1.000000,68.350000,8.610000,1.150000,38.600000,-60.390000,21.400000,-17.990000,-31.270000,14.910000
25%,183.250000,7.754178e+05,905.000000,65.255000,89.000000,4.420277e+03,123.250000,96.550000,34.637500,20.562500,68.292500,46.287500,85.050000,27.280000,22.282500,49.780000
50%,335.500000,1.498161e+06,948.000000,72.150000,216.500000,6.264860e+03,222.500000,98.500000,48.040000,34.600000,75.730000,60.250000,92.160000,32.310000,29.120000,56.940000
75%,487.750000,2.423572e+06,982.000000,79.987500,353.750000,9.064698e+03,309.000000,99.410000,70.110000,54.047500,83.135000,74.315000,97.192500,38.765000,35.407500,62.635000
max,640.000000,1.106015e+07,1184.000000,97.910000,1166.000000,9.621551e+06,361.000000,100.000000,98.680000,97.790000,99.720000,98.650000,100.000000,60.610000,62.380000,84.840000

In [ ]:
df.isnull().sum()

ranking                          0
district                         0
state                            0
population                       0
growth                           0
sex_ratio                        0
literacy                         0
health_centres                   0
population_per_health_centre     0
healthcare_density               0
healthcare_rank                  0
electricity                      0
clean_fuel                       0
health_insurance                 0
female_literacy                  0
antenatal_care                   0
institutional_birth              0
vaccination                     55
stunted                          0
underweight                      0
anaemia                          0
dtype: int64

In [ ]:
print("Total States :",df["state"].nunique())

print("Total Districts :",df["district"].nunique())

print("Total Population :",df["population"].sum())

print("Total Health Centres :",df["health_centres"].sum())

print("Average Literacy :",round(df["literacy"].mean(),2))

df["vaccination"] = pd.to_numeric(df["vaccination"], errors='coerce')
print("Average Vaccination :",round(df["vaccination"].mean(),2))

print("Average Anaemia :",round(df["anaemia"].mean(),2))

Total States : 35
Total Districts : 604
Total Population : 1125461384.0
Total Health Centres : 150387.0
Average Literacy : 72.34
Average Vaccination : 24.58
Average Anaemia : 55.52

In [ ]:
top=df.sort_values("population",ascending=False).head(20)

fig=px.bar(
top,
x="district",
y="population",
color="population",
title="Top 20 Most Populated Districts"
)

fig.show()

In [ ]:
state_pop=df.groupby("state")["population"].sum().reset_index()

fig=px.bar(

state_pop.sort_values("population",ascending=False),

x="state",

y="population",

title="State-wise Population"

)

fig.show()

In [ ]:
state_health=df.groupby("state")["health_centres"].sum().reset_index()

fig=px.bar(

state_health.sort_values("health_centres",ascending=False),

x="state",

y="health_centres",

color="health_centres",

title="Health Centres by State"

)

fig.show()

In [ ]:
top=df.sort_values(

"population_per_health_centre",

ascending=False

).head(20)

fig=px.bar(

top,

x="district",

y="population_per_health_centre",

color="population_per_health_centre",

title="Highest Healthcare Pressure"

)

fig.show()

In [ ]:
lowest=df.sort_values("vaccination").head(20)

fig=px.bar(

lowest,

x="district",

y="vaccination",

color="vaccination",

title="Lowest Vaccination Districts"

)

fig.show()

In [ ]:
vacc=df.groupby("state")["vaccination"].mean().reset_index()

fig=px.bar(

vacc.sort_values("vaccination",ascending=False),

x="state",

y="vaccination",

title="Average Vaccination by State"

)

fig.show()

In [ ]:
anaemia=df.sort_values("anaemia",ascending=False).head(20)

fig=px.bar(

anaemia,

x="district",

y="anaemia",

color="anaemia",

title="Highest Anaemia Districts"

)

fig.show()

In [ ]:
birth=df.groupby("state")["institutional_birth"].mean().reset_index()

fig=px.bar(

birth.sort_values("institutional_birth"),

x="state",

y="institutional_birth",

title="Institutional Birth Rate"

)

fig.show()

In [ ]:
antenatal=df.groupby("state")["antenatal_care"].mean().reset_index()

fig=px.bar(

antenatal.sort_values("antenatal_care"),

x="state",

y="antenatal_care",

title="Antenatal Care Coverage"

)

fig.show()

In [ ]:
stunted=df.sort_values("stunted",ascending=False).head(20)

fig=px.bar(

stunted,

x="district",

y="stunted",

title="Highest Child Stunting"

)

fig.show()

In [ ]:
under=df.sort_values("underweight",ascending=False).head(20)

fig=px.bar(

under,

x="district",

y="underweight",

title="Highest Underweight Children"

)

fig.show()

In [ ]:
female=df.groupby("state")["female_literacy"].mean().reset_index()

fig=px.bar(

female.sort_values("female_literacy"),

x="state",

y="female_literacy",

title="Female Literacy"

)

fig.show()

In [ ]:
corr=df.select_dtypes(include=np.number).corr()

fig=px.imshow(

corr,

text_auto=True,

title="Correlation Matrix"

)

fig.show()

In [ ]:
priority=df.sort_values(

"population_per_health_centre",

ascending=False

)[["district","state","population_per_health_centre"]]

priority.head(20)

               district           state  population_per_health_centre
2             BANGALORE       KARNATAKA                     9621551.0
4       MUMBAI SUBURBAN     MAHARASHTRA                     9356962.0
7             AHMADABAD         GUJARAT                     7214225.0
16           RANGAREDDY  ANDHRA PRADESH                     5296741.0
19      PURBI CHAMPARAN           BIHAR                     5099371.0
32           AHMADNAGAR     MAHARASHTRA                     4543159.0
34              KOLKATA     WEST BENGAL                     4496694.0
43        VISAKHAPATNAM  ANDHRA PRADESH                     4290589.0
54          MAHBUBNAGAR  ANDHRA PRADESH                     4053028.0
55                KHERI   UTTAR PRADESH                     4021243.0
59            HYDERABAD  ANDHRA PRADESH                     3943323.0
63   PASHCHIM CHAMPARAN           BIHAR                     3935042.0
68           KARIMNAGAR  ANDHRA PRADESH                     3776269.0
77     NORTH WEST DELHI           DELHI                     3656539.0
82             WARANGAL  ANDHRA PRADESH                     3512576.0
87             NALGONDA  ANDHRA PRADESH                     3488809.0
110         BANASKANTHA         GUJARAT                     3120506.0
111               UNNAO   UTTAR PRADESH                     3108367.0
113           KOZHIKODE          KERALA                     3086293.0
114         MUMBAI CITY     MAHARASHTRA                     3085411.0

In [ ]:
best=df.sort_values(

"population_per_health_centre"

).head(20)

best

,ranking,district,state,population,growth,sex_ratio,literacy,health_centres,population_per_health_centre,healthcare_density,healthcare_rank,electricity,clean_fuel,health_insurance,female_literacy,antenatal_care,institutional_birth,vaccination,stunted,underweight,anaemia
573,604,KARGIL,JAMMU AND KASHMIR,140802.0,18.02 %,810,71.34,138.0,1020.304348,Excellent,278.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
608,639,ANJAW,ARUNACHAL PRADESH,21167.0,14.19 %,839,56.46,17.0,1245.117647,Excellent,353.0,96.39,29.01,17.47,67.89,32.32,77.95,-92.99,23.56,16.01,35.86
609,640,DIBANG VALLEY,ARUNACHAL PRADESH,8004.0,10.07 %,813,64.10,6.0,1334.000000,Excellent,359.0,79.23,49.26,28.69,77.83,40.38,85.52,-90.71,16.88,15.95,62.87
588,619,KINNAUR,HIMACHAL PRADESH,84121.0,7.39 %,819,80.00,62.0,1356.790323,Excellent,328.0,99.58,70.38,35.91,89.11,75.32,82.72,-91.73,32.16,18.92,51.72
572,603,NEW DELHI,DELHI,142004.0,-20.72 %,822,88.34,88.0,1613.681818,Excellent,310.0,100.00,98.33,25.18,83.85,80.06,91.76,82.17,27.35,20.66,55.96
579,610,CHAMPHAI,MIZORAM,125745.0,16.01 %,984,95.91,73.0,1722.534247,Excellent,321.0,100.00,79.44,64.92,97.73,63.43,96.67,-85.25,27.22,13.08,25.74
606,637,UPPER SIANG,ARUNACHAL PRADESH,35320.0,5.87 %,889,59.99,20.0,1766.000000,Excellent,352.0,99.46,36.32,34.60,74.37,34.01,75.98,-61.42,30.37,12.00,29.17
566,597,LUNGLEI,MIZORAM,161428.0,17.64 %,947,88.86,84.0,1921.761905,Excellent,312.0,97.96,79.88,46.52,91.58,56.72,82.69,-73.84,26.46,11.06,34.85
597,628,SAIHA,MIZORAM,56574.0,-7.34 %,979,90.01,29.0,1950.827586,Excellent,346.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
595,626,SERCHHIP,MIZORAM,64937.0,20.56 %,977,97.91,33.0,1967.787879,Excellent,342.0,99.31,81.78,58.83,99.72,60.25,96.18,84.67,31.77,14.39,32.12
583,614,NORTH AND MIDDLE ANDAMAN,ANDAMAN AND NICOBAR ISLANDS,105597.0,-0.02 %,925,83.91,52.0,2030.711538,Excellent,333.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
555,586,KISHTWAR,JAMMU AND KASHMIR,230696.0,20.88 %,920,56.20,113.0,2041.557522,Excellent,293.0,88.82,50.60,16.37,71.28,76.40,91.59,-91.61,27.49,17.74,84.84
587,618,MAMIT,MIZORAM,86364.0,37.56 %,927,84.93,41.0,2106.439024,Excellent,340.0,97.93,73.27,61.70,89.63,52.48,74.96,85.87,26.41,13.93,34.89
513,544,CHAMBA,HIMACHAL PRADESH,519080.0,12.63 %,986,72.17,228.0,2276.666667,Excellent,215.0,99.09,34.96,26.79,84.09,62.71,72.04,-100.00,42.56,25.96,43.71
452,483,SHIMLA,HIMACHAL PRADESH,814010.0,12.67 %,915,83.64,356.0,2286.544944,Excellent,121.0,100.00,78.02,37.07,93.36,85.31,92.23,-96.53,27.07,14.93,46.49
532,563,BILASPUR,HIMACHAL PRADESH,381956.0,12.05 %,981,84.59,164.0,2329.000000,Excellent,261.0,99.97,35.78,35.41,91.23,81.35,91.70,-100.00,40.06,38.77,52.99
576,607,NARAYANPUR,CHHATTISGARH,139820.0,19.16 %,994,48.62,60.0,2330.333333,Excellent,329.0,90.05,19.52,83.09,53.84,59.10,74.16,81.67,43.73,39.49,71.97
508,539,KODAGU,KARNATAKA,554519.0,1.09 %,1019,82.61,236.0,2349.656780,Excellent,209.0,98.72,78.32,45.63,88.50,74.36,98.43,-90.56,30.41,22.59,39.85
521,552,HAMIRPUR,HIMACHAL PRADESH,454768.0,10.19 %,1095,88.15,193.0,2356.310881,Excellent,240.0,99.66,44.73,32.03,94.84,59.43,97.60,-74.25,27.27,23.58,49.45
539,570,REASI,JAMMU AND KASHMIR,314667.0,27.04 %,890,58.15,133.0,2365.917293,Excellent,281.0,99.91,35.20,11.24,68.19,75.92,69.32,79.05,17.74,11.73,62.88

In [ ]:
worst=df.sort_values(

"population_per_health_centre",

ascending=False

).head(20)

worst

,ranking,district,state,population,growth,sex_ratio,literacy,health_centres,population_per_health_centre,healthcare_density,healthcare_rank,electricity,clean_fuel,health_insurance,female_literacy,antenatal_care,institutional_birth,vaccination,stunted,underweight,anaemia
2,3,BANGALORE,KARNATAKA,9621551.0,47.18 %,916,87.67,0.0,9621551.0,Critical,361.0,98.78,97.20,28.83,87.27,74.60,99.34,-78.16,31.26,28.09,35.54
4,5,MUMBAI SUBURBAN,MAHARASHTRA,9356962.0,8.29 %,860,89.91,0.0,9356962.0,Critical,361.0,99.17,98.68,20.19,91.58,72.20,98.08,NaN,37.23,24.59,49.97
7,8,AHMADABAD,GUJARAT,7214225.0,24.03 %,904,85.31,0.0,7214225.0,Critical,361.0,99.49,89.72,36.23,81.47,77.76,94.45,-65.23,35.45,33.97,63.70
16,17,RANGAREDDY,ANDHRA PRADESH,5296741.0,48.16 %,961,75.87,0.0,5296741.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
19,20,PURBI CHAMPARAN,BIHAR,5099371.0,29.43 %,902,55.79,0.0,5099371.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
32,33,AHMADNAGAR,MAHARASHTRA,4543159.0,12.44 %,939,79.05,0.0,4543159.0,Critical,361.0,94.48,77.44,12.03,86.19,76.61,97.90,83.53,31.68,41.19,50.30
34,35,KOLKATA,WEST BENGAL,4496694.0,-1.67 %,908,86.31,0.0,4496694.0,Critical,361.0,99.59,91.71,21.08,87.60,71.74,97.47,-80.16,29.63,32.91,58.18
43,44,VISAKHAPATNAM,ANDHRA PRADESH,4290589.0,11.96 %,1006,66.91,0.0,4290589.0,Critical,361.0,99.57,72.87,64.92,69.54,58.59,95.25,-76.49,30.96,33.53,58.02
54,55,MAHBUBNAGAR,ANDHRA PRADESH,4053028.0,15.34 %,977,55.04,0.0,4053028.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
55,56,KHERI,UTTAR PRADESH,4021243.0,25.38 %,894,60.56,0.0,4021243.0,Critical,361.0,84.15,35.91,22.01,61.99,47.98,82.77,69.49,47.59,36.29,52.95
59,60,HYDERABAD,ANDHRA PRADESH,3943323.0,2.97 %,954,83.25,0.0,3943323.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
63,64,PASHCHIM CHAMPARAN,BIHAR,3935042.0,29.29 %,909,55.70,0.0,3935042.0,Critical,361.0,93.45,31.42,19.96,52.53,25.39,79.45,62.07,43.47,30.26,50.58
68,69,KARIMNAGAR,ANDHRA PRADESH,3776269.0,8.15 %,1008,64.15,0.0,3776269.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
77,78,NORTH WEST DELHI,DELHI,3656539.0,27.81 %,865,84.45,0.0,3656539.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
82,83,WARANGAL,ANDHRA PRADESH,3512576.0,8.21 %,997,65.11,0.0,3512576.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
87,88,NALGONDA,ANDHRA PRADESH,3488809.0,7.41 %,983,64.20,0.0,3488809.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
110,111,BANASKANTHA,GUJARAT,3120506.0,24.61 %,938,65.32,0.0,3120506.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94
111,112,UNNAO,UTTAR PRADESH,3108367.0,15.11 %,907,66.37,0.0,3108367.0,Critical,361.0,75.36,43.44,15.33,68.18,19.76,80.84,58.57,39.17,29.25,48.92
113,114,KOZHIKODE,KERALA,3086293.0,7.20 %,1098,95.08,0.0,3086293.0,Critical,361.0,99.60,73.83,61.11,99.05,91.75,100.00,-88.78,21.31,18.85,29.83
114,115,MUMBAI CITY,MAHARASHTRA,3085411.0,-7.57 %,832,89.21,0.0,3085411.0,Critical,361.0,98.50,48.04,34.60,75.73,60.25,92.16,NaN,32.31,29.12,56.94

In [ ]:
priority.to_csv(

"high_priority_districts.csv",

index=False

)