In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)

In [ ]:
df = pd.read_csv("healthcare_priority_index.csv")

df.head()

,ranking,district,state,population,growth,sex_ratio,literacy,health_centres,population_per_health_centre,healthcare_density,healthcare_rank,electricity,clean_fuel,health_insurance,female_literacy,antenatal_care,institutional_birth,vaccination,stunted,underweight,anaemia,healthcare_priority_score,priority_level,priority_rank
0,1,THANE,MAHARASHTRA,11060148.0,36.01 %,886,84.53,336.0,0.003315,Poor,134.0,99.29,90.40,22.73,0.151014,0.178949,0.081170,0.873284,0.747455,0.662894,0.627914,43.143000,Medium,72
1,2,NORTH TWENTY FOUR PARGANAS,WEST BENGAL,10009781.0,12.04 %,955,84.06,870.0,0.001090,Average,7.0,98.50,48.04,34.60,0.392507,0.241449,0.099746,0.146204,0.639949,0.644848,0.601030,28.488685,Low,430
2,3,BANGALORE,KARNATAKA,9621551.0,47.18 %,916,87.67,0.0,1.000000,Critical,361.0,98.78,97.20,28.83,0.203698,0.151220,0.008397,0.889742,0.626590,0.633849,0.295009,66.640940,High,1
3,4,PUNE,MAHARASHTRA,9429408.0,30.37 %,915,86.15,773.0,0.001162,Average,16.0,99.37,89.49,14.42,0.175229,0.189009,0.025827,0.788368,0.619466,0.682648,0.529387,38.714485,Low,161
4,5,MUMBAI SUBURBAN,MAHARASHTRA,9356962.0,8.29 %,860,89.91,0.0,0.972497,Critical,361.0,99.17,98.68,20.19,0.133181,0.166310,0.024427,0.146204,0.702545,0.596476,0.501359,54.229173,Medium,5

In [ ]:
def generate_recommendation(row):

    recommendations = []

    if row["population_per_health_centre"] > 30000:
        recommendations.append("Build New PHCs")

    if row["health_centres"] < 5:
        recommendations.append("Recruit Additional Doctors & Nurses")

    if row["vaccination"] < 70:
        recommendations.append("Launch Vaccination Campaign")

    if row["anaemia"] > 50:
        recommendations.append("Start Nutrition & Anaemia Control Programme")

    if row["female_literacy"] < 70:
        recommendations.append("Women's Health Awareness Programme")

    if row["antenatal_care"] < 60:
        recommendations.append("Improve Maternal Healthcare Services")

    if row["institutional_birth"] < 70:
        recommendations.append("Strengthen Institutional Delivery Facilities")

    if row["stunted"] > 35:
        recommendations.append("Child Nutrition Improvement Programme")

    if row["underweight"] > 30:
        recommendations.append("School Nutrition Initiative")

    if len(recommendations)==0:
        recommendations.append("Current Healthcare Infrastructure is Satisfactory")

    return " | ".join(recommendations)

In [ ]:
df["government_recommendation"] = df.apply(
    generate_recommendation,
    axis=1
)

In [ ]:
df[[
    "district",
    "state",
    "priority_level",
    "government_recommendation"
]].head(20)

,district,state,priority_level,government_recommendation
0,THANE,MAHARASHTRA,Medium,Launch Vaccination Campaign | Women's Health A...
1,NORTH TWENTY FOUR PARGANAS,WEST BENGAL,Low,Launch Vaccination Campaign | Women's Health A...
2,BANGALORE,KARNATAKA,High,Recruit Additional Doctors & Nurses | Launch V...
3,PUNE,MAHARASHTRA,Low,Launch Vaccination Campaign | Women's Health A...
4,MUMBAI SUBURBAN,MAHARASHTRA,Medium,Recruit Additional Doctors & Nurses | Launch V...
5,SOUTH TWENTY FOUR PARGANAS,WEST BENGAL,Low,Launch Vaccination Campaign | Women's Health A...
6,BARDDHAMAN,WEST BENGAL,Low,Launch Vaccination Campaign | Women's Health A...
7,AHMADABAD,GUJARAT,High,Recruit Additional Doctors & Nurses | Launch V...
8,MURSHIDABAD,WEST BENGAL,Low,Launch Vaccination Campaign | Women's Health A...
9,JAIPUR,RAJASTHAN,Low,Launch Vaccination Campaign | Women's Health A...
10,NASHIK,MAHARASHTRA,Low,Launch Vaccination Campaign | Women's Health A...
11,SURAT,GUJARAT,Medium,Launch Vaccination Campaign | Women's Health A...
12,ALLAHABAD,UTTAR PRADESH,Low,Launch Vaccination Campaign | Women's Health A...
13,PASCHIM MEDINIPUR,WEST BENGAL,Low,Launch Vaccination Campaign | Women's Health A...
14,PATNA,BIHAR,Low,Launch Vaccination Campaign | Women's Health A...
15,HUGLI,WEST BENGAL,Medium,Launch Vaccination Campaign | Women's Health A...
16,RANGAREDDY,ANDHRA PRADESH,Medium,Recruit Additional Doctors & Nurses | Launch V...
17,NADIA,WEST BENGAL,Medium,Launch Vaccination Campaign | Women's Health A...
18,EAST GODAVARI,ANDHRA PRADESH,Medium,Launch Vaccination Campaign | Women's Health A...
19,PURBI CHAMPARAN,BIHAR,Medium,Recruit Additional Doctors & Nurses | Launch V...

In [ ]:
recommendation_counts = (
    df["government_recommendation"]
    .str.split(" \\| ")
    .explode()
    .value_counts()
    .reset_index()
)

recommendation_counts.columns = [
    "Recommendation",
    "Count"
]

recommendation_counts

                                 Recommendation  Count
0                   Launch Vaccination Campaign    610
1            Women's Health Awareness Programme    610
2          Improve Maternal Healthcare Services    610
3  Strengthen Institutional Delivery Facilities    610
4           Recruit Additional Doctors & Nurses     80

In [ ]:
import plotly.express as px

fig = px.bar(
    recommendation_counts,
    x="Recommendation",
    y="Count",
    color="Count",
    title="Government Policy Recommendation Distribution"
)

fig.show()

In [ ]:
critical = (

df

[df["priority_level"]=="Critical"]

.sort_values(

"healthcare_priority_score",

ascending=False

)

)

critical.head(25)

Empty DataFrame
Columns: [ranking, district, state, population, growth, sex_ratio, literacy, health_centres, population_per_health_centre, healthcare_density, healthcare_rank, electricity, clean_fuel, health_insurance, female_literacy, antenatal_care, institutional_birth, vaccination, stunted, underweight, anaemia, healthcare_priority_score, priority_level, priority_rank, government_recommendation]
Index: []

In [ ]:
executive_report = df[[

"district",

"state",

"healthcare_priority_score",

"priority_level",

"government_recommendation"

]]

executive_report.head(20)

,district,state,healthcare_priority_score,priority_level,government_recommendation
0,THANE,MAHARASHTRA,43.143000,Medium,Launch Vaccination Campaign | Women's Health A...
1,NORTH TWENTY FOUR PARGANAS,WEST BENGAL,28.488685,Low,Launch Vaccination Campaign | Women's Health A...
2,BANGALORE,KARNATAKA,66.640940,High,Recruit Additional Doctors & Nurses | Launch V...
3,PUNE,MAHARASHTRA,38.714485,Low,Launch Vaccination Campaign | Women's Health A...
4,MUMBAI SUBURBAN,MAHARASHTRA,54.229173,Medium,Recruit Additional Doctors & Nurses | Launch V...
5,SOUTH TWENTY FOUR PARGANAS,WEST BENGAL,28.474635,Low,Launch Vaccination Campaign | Women's Health A...
6,BARDDHAMAN,WEST BENGAL,28.479487,Low,Launch Vaccination Campaign | Women's Health A...
7,AHMADABAD,GUJARAT,65.716041,High,Recruit Additional Doctors & Nurses | Launch V...
8,MURSHIDABAD,WEST BENGAL,32.889775,Low,Launch Vaccination Campaign | Women's Health A...
9,JAIPUR,RAJASTHAN,24.065228,Low,Launch Vaccination Campaign | Women's Health A...
10,NASHIK,MAHARASHTRA,30.692988,Low,Launch Vaccination Campaign | Women's Health A...
11,SURAT,GUJARAT,46.168100,Medium,Launch Vaccination Campaign | Women's Health A...
12,ALLAHABAD,UTTAR PRADESH,30.060990,Low,Launch Vaccination Campaign | Women's Health A...
13,PASCHIM MEDINIPUR,WEST BENGAL,34.553332,Low,Launch Vaccination Campaign | Women's Health A...
14,PATNA,BIHAR,35.526461,Low,Launch Vaccination Campaign | Women's Health A...
15,HUGLI,WEST BENGAL,48.179301,Medium,Launch Vaccination Campaign | Women's Health A...
16,RANGAREDDY,ANDHRA PRADESH,44.969799,Medium,Recruit Additional Doctors & Nurses | Launch V...
17,NADIA,WEST BENGAL,46.106361,Medium,Launch Vaccination Campaign | Women's Health A...
18,EAST GODAVARI,ANDHRA PRADESH,40.630678,Medium,Launch Vaccination Campaign | Women's Health A...
19,PURBI CHAMPARAN,BIHAR,44.354334,Medium,Recruit Additional Doctors & Nurses | Launch V...

In [ ]:
executive_report.to_csv(

"government_policy_recommendations.csv",

index=False

)